In [2]:
# 필요한 라이브러리 설치 및 임포트
!pip install pandas

import pandas as pd
import datetime

Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (1.0.5)
Requirement already satisfied: pytz>=2017.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2020.1)
Requirement already satisfied: numpy>=1.13.3 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.18.5)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas) (1.15.0)

---

# [Step 2] 데이터 전처리

#### **<span style="color:blue">[2-0] air_21, air_22, weather_21, weather_22 데이터 로딩</span>**

In [63]:
# 데이터 로딩

air_21 = pd.read_csv("C:/Users/admin/Desktop/에이블 실습/miniproject2/air_2021.csv", sep=',', index_col = 0, encoding = 'utf-8' )
air_22 = pd.read_csv("C:/Users/admin/Desktop/에이블 실습/miniproject2/air_2022.csv", sep=',', index_col = 0, encoding = 'utf-8' )
weather_21 = pd.read_csv("C:/Users/admin/Desktop/에이블 실습/miniproject2/weather_2021.csv", sep = ',', encoding='cp949')
weather_22 = pd.read_csv("C:/Users/admin/Desktop/에이블 실습/miniproject2/weather_2022.csv", sep = ',', encoding='cp949')

#### **<span style="color:blue">[2-1] air_21, air_22 의 '측정일시'를 활용하여 'time' 변수 생성</span>**

In [64]:
weather_21.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8759 entries, 0 to 8758
Data columns (total 38 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   지점             8759 non-null   int64
 1   지점명            8759 non-null   object
 2   일시             8759 non-null   object
 3   기온(°C)         8759 non-null   float64
 4   기온 QC플래그       0 non-null      float64
 5   강수량(mm)        949 non-null    float64
 6   강수량 QC플래그      1763 non-null   float64
 7   풍속(m/s)        8757 non-null   float64
 8   풍속 QC플래그       2 non-null      float64
 9   풍향(16방위)       8757 non-null   float64
 10  풍향 QC플래그       2 non-null      float64
 11  습도(%)          8759 non-null   int64
 12  습도 QC플래그       0 non-null      float64
 13  증기압(hPa)       8759 non-null   float64
 14  이슬점온도(°C)      8759 non-null   float64
 15  현지기압(hPa)      8759 non-null   float64
 16  현지기압 QC플래그     0 non-null      float64
 17  해면기압(hPa)      8759 non-null   float64
 18  해면기압 QC플래그     0 non-null      float64
 19  일조(hr)         4791 non-null   float64
 20  일조 QC플래그       3968 non-null   float64
 21  일사(MJ/m2)      4791 non-null   float64
 22  일사 QC플래그       3968 non-null   float64
 23  적설(cm)         379 non-null    float64
 24  3시간신적설(cm)     29 non-null     float64
 25  전운량(10분위)      8757 non-null   float64
 26  중하층운량(10분위)    8759 non-null   int64
 27  운형(운형약어)       4947 non-null   object
 28  최저운고(100m )    4547 non-null   float64
 29  시정(10m)        8759 non-null   int64
 30  지면상태(지면상태코드)   0 non-null      float64
 31  현상번호(국내식)      2125 non-null   float64
 32  지면온도(°C)       8754 non-null   float64
 33  지면온도 QC플래그     24 non-null     float64
 34  5cm 지중온도(°C)   8754 non-null   float64
 35  10cm 지중온도(°C)  8754 non-null   float64
 36  20cm 지중온도(°C)  8754 non-null   float64
 37  30cm 지중온도(°C)  8754 non-null   float64
dtypes: float64(31), int64(4), object(3)
memory usage: 2.5+ MB

In [65]:
air_21.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8760 entries, 0 to 8759
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      8760 non-null   object
 1   망       8760 non-null   object
 2   측정소코드   8760 non-null   int64
 3   측정소명    8760 non-null   object
 4   측정일시    8760 non-null   int64
 5   SO2     8648 non-null   float64
 6   CO      8680 non-null   float64
 7   O3      8663 non-null   float64
 8   NO2     8680 non-null   float64
 9   PM10    8655 non-null   float64
 10  PM25    8663 non-null   float64
 11  주소      8760 non-null   object
dtypes: float64(6), int64(2), object(4)
memory usage: 889.7+ KB

* air_21, air_22 의 '측정일시'를 활용하여 'time'변수 생성
* time 변수를 to_datetime으로 데이터 타입 변경
* 참고: 미세먼지 데이터는 1시-24시, 날씨 데이터는 0시-23시로 구성되어 있습니다. [2-5]에서 미세먼지와 날씨 데이터를 time 기준으로 합치려면 날씨 기준이 동일해야 합니다. 미세먼지 데이터에서 time 변수 생성 시 이를 미리 고려(예:측정일시 값 -1)하세요.

In [82]:
# 아래에 필요한 코드를 작성하고 결과를 확인합니다.

air_21['time'] = air_21['측정일시']-1
air_21['time'] = air_21['time'].astype('str')
air_22['time'] = air_22['측정일시']-1
air_22['time'] = air_22['time'].astype('str')

In [83]:
air_21['time'] = pd.to_datetime(air_21['time'], format = '%Y%m%d%H')
air_22['time'] = pd.to_datetime(air_22['time'], format = '%Y%m%d%H')

In [92]:
air_21

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소,time
0,서울 종로구,도시대기,111123,종로구,2021100101,0.003,0.6,0.002,0.039,31.0,18.0,서울 종로구 종로35가길 19,2021-10-01 00:00:00
1,서울 종로구,도시대기,111123,종로구,2021100102,0.003,0.6,0.002,0.035,27.0,16.0,서울 종로구 종로35가길 19,2021-10-01 01:00:00
2,서울 종로구,도시대기,111123,종로구,2021100103,0.003,0.6,0.002,0.033,28.0,18.0,서울 종로구 종로35가길 19,2021-10-01 02:00:00
3,서울 종로구,도시대기,111123,종로구,2021100104,0.003,0.6,0.002,0.030,26.0,16.0,서울 종로구 종로35가길 19,2021-10-01 03:00:00
4,서울 종로구,도시대기,111123,종로구,2021100105,0.003,0.5,0.003,0.026,26.0,16.0,서울 종로구 종로35가길 19,2021-10-01 04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,서울 종로구,도시대기,111123,종로구,2021093020,0.003,0.7,0.020,0.036,35.0,24.0,서울 종로구 종로35가길 19,2021-09-30 19:00:00
8756,서울 종로구,도시대기,111123,종로구,2021093021,0.003,0.6,0.016,0.035,34.0,21.0,서울 종로구 종로35가길 19,2021-09-30 20:00:00
8757,서울 종로구,도시대기,111123,종로구,2021093022,0.003,0.6,0.012,0.036,30.0,19.0,서울 종로구 종로35가길 19,2021-09-30 21:00:00
8758,서울 종로구,도시대기,111123,종로구,2021093023,0.003,0.6,0.004,0.042,33.0,19.0,서울 종로구 종로35가길 19,2021-09-30 22:00:00
8759,서울 종로구,도시대기,111123,종로구,2021093024,0.003,0.6,0.003,0.042,29.0,17.0,서울 종로구 종로35가길 19,2021-09-30 23:00:00

#### **<span style="color:blue">[2-2] weather_21, weather_22 의 '일시'를 활용하여 'time' 변수 생성</span>**

* weather_21, weather_22 의 '일시'를 활용하여 'time'변수 생성
* time 변수를 to_datetime으로 데이터 타입 변경

In [93]:
weather_21

,지점,지점명,일시,기온(°C),기온 QC플래그,강수량(mm),강수량 QC플래그,풍속(m/s),풍속 QC플래그,풍향(16방위),...,시정(10m),지면상태(지면상태코드),현상번호(국내식),지면온도(°C),지면온도 QC플래그,5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C),time
0,108,서울,2021-01-01 01:00,-8.7,NaN,NaN,NaN,2.4,NaN,270.0,...,2000,NaN,NaN,-6.9,NaN,-1.0,-0.8,0.3,1.6,2021-01-01 01:00:00
1,108,서울,2021-01-01 02:00,-9.1,NaN,NaN,NaN,1.6,NaN,270.0,...,2000,NaN,NaN,-7.1,NaN,-1.1,-0.8,0.3,1.6,2021-01-01 02:00:00
2,108,서울,2021-01-01 03:00,-9.3,NaN,NaN,NaN,1.1,NaN,250.0,...,2000,NaN,NaN,-7.3,NaN,-1.2,-0.9,0.3,1.6,2021-01-01 03:00:00
3,108,서울,2021-01-01 04:00,-9.3,NaN,NaN,NaN,0.3,NaN,0.0,...,2000,NaN,NaN,-7.5,NaN,-1.3,-1.0,0.2,1.5,2021-01-01 04:00:00
4,108,서울,2021-01-01 05:00,-9.7,NaN,NaN,NaN,1.9,NaN,20.0,...,2000,NaN,NaN,-7.6,NaN,-1.3,-1.0,0.2,1.5,2021-01-01 05:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8754,108,서울,2021-12-31 19:00,-6.4,NaN,NaN,NaN,2.2,NaN,250.0,...,2000,NaN,NaN,-4.5,NaN,-0.5,-0.7,-0.1,1.0,2021-12-31 19:00:00
8755,108,서울,2021-12-31 20:00,-6.3,NaN,NaN,NaN,4.1,NaN,320.0,...,2000,NaN,NaN,-5.3,NaN,-0.6,-0.8,-0.1,1.0,2021-12-31 20:00:00
8756,108,서울,2021-12-31 21:00,-6.7,NaN,NaN,NaN,4.8,NaN,320.0,...,2000,NaN,NaN,-5.7,NaN,-0.7,-0.8,-0.1,1.0,2021-12-31 21:00:00
8757,108,서울,2021-12-31 22:00,-7.5,NaN,NaN,NaN,3.0,NaN,320.0,...,2000,NaN,NaN,-6.2,NaN,-0.8,-0.9,-0.2,1.0,2021-12-31 22:00:00
8758,108,서울,2021-12-31 23:00,-7.7,NaN,NaN,NaN,2.9,NaN,320.0,...,2000,NaN,NaN,-6.5,NaN,-0.9,-0.9,-0.2,1.0,2021-12-31 23:00:00

In [86]:
# 아래에 필요한 코드를 작성하고 결과를 확인합니다.
weather_21['time'] = weather_21['일시']
weather_22['time'] = weather_22['일시']

In [87]:
weather_21['time'] = pd.to_datetime(weather_21['time'], format = '%Y-%m-%d %H')
weather_22['time'] = pd.to_datetime(weather_22['time'], format = '%Y-%m-%d %H')

In [88]:
weather_21.head()

,지점,지점명,일시,기온(°C),기온 QC플래그,강수량(mm),강수량 QC플래그,풍속(m/s),풍속 QC플래그,풍향(16방위),...,시정(10m),지면상태(지면상태코드),현상번호(국내식),지면온도(°C),지면온도 QC플래그,5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C),time
0,108,서울,2021-01-01 01:00,-8.7,NaN,NaN,NaN,2.4,NaN,270.0,...,2000,NaN,NaN,-6.9,NaN,-1.0,-0.8,0.3,1.6,2021-01-01 01:00:00
1,108,서울,2021-01-01 02:00,-9.1,NaN,NaN,NaN,1.6,NaN,270.0,...,2000,NaN,NaN,-7.1,NaN,-1.1,-0.8,0.3,1.6,2021-01-01 02:00:00
2,108,서울,2021-01-01 03:00,-9.3,NaN,NaN,NaN,1.1,NaN,250.0,...,2000,NaN,NaN,-7.3,NaN,-1.2,-0.9,0.3,1.6,2021-01-01 03:00:00
3,108,서울,2021-01-01 04:00,-9.3,NaN,NaN,NaN,0.3,NaN,0.0,...,2000,NaN,NaN,-7.5,NaN,-1.3,-1.0,0.2,1.5,2021-01-01 04:00:00
4,108,서울,2021-01-01 05:00,-9.7,NaN,NaN,NaN,1.9,NaN,20.0,...,2000,NaN,NaN,-7.6,NaN,-1.3,-1.0,0.2,1.5,2021-01-01 05:00:00

---

#### **<span style="color:blue">[2-3] 'time' 기준으로 데이터 합치기</span>**

* 미세먼지 데이터와 날씨 데이터를 'time' 기준으로 합쳐보세요.
* df_21에는 'time' 기준으로 21년도 미세먼지, 날씨 데이터를 합쳐보세요.
* df_22에는 'time' 기준으로 22년도 미세먼지, 날씨 데이터를 합쳐보세요.

In [124]:
# 아래에 필요한 코드를 작성하고 결과를 확인합니다.
df_21 = pd.merge(weather_21, air_21, how = 'inner', on = 'time')
df_22 = pd.merge(weather_22, air_22, how = 'inner', on = 'time')

In [125]:
df_21.columns

Index(['지점', '지점명', '일시', '기온(°C)', '기온 QC플래그', '강수량(mm)', '강수량 QC플래그',
       '풍속(m/s)', '풍속 QC플래그', '풍향(16방위)', '풍향 QC플래그', '습도(%)', '습도 QC플래그',
       '증기압(hPa)', '이슬점온도(°C)', '현지기압(hPa)', '현지기압 QC플래그', '해면기압(hPa)',
       '해면기압 QC플래그', '일조(hr)', '일조 QC플래그', '일사(MJ/m2)', '일사 QC플래그', '적설(cm)',
       '3시간신적설(cm)', '전운량(10분위)', '중하층운량(10분위)', '운형(운형약어)', '최저운고(100m )',
       '시정(10m)', '지면상태(지면상태코드)', '현상번호(국내식)', '지면온도(°C)', '지면온도 QC플래그',
       '5cm 지중온도(°C)', '10cm 지중온도(°C)', '20cm 지중온도(°C)', '30cm 지중온도(°C)',
       'time', '지역', '망', '측정소코드', '측정소명', '측정일시', 'SO2', 'CO', 'O3', 'NO2',
       'PM10', 'PM25', '주소'],
      dtype='object')

---

#### **<span style="color:blue">[2-4] 사용하지 않을 변수 제거</span>**

* 머신러닝에 사용하지 않을 변수들을 제거해줍니다.
* df_21, df_22에 사용할 변수들만 넣어보세요.

In [126]:
# df_21, df_22에 사용할 변수들만 할당
drop_cols = ['지점', '지점명', '일시', '기온 QC플래그','강수량 QC플래그',
        '풍속 QC플래그',  '풍향 QC플래그',  '습도 QC플래그',
       '증기압(hPa)', '이슬점온도(°C)', '현지기압(hPa)', '현지기압 QC플래그', '해면기압(hPa)',
       '해면기압 QC플래그', '일조(hr)', '일조 QC플래그', '일사(MJ/m2)', '일사 QC플래그', '적설(cm)',
       '3시간신적설(cm)', '전운량(10분위)', '중하층운량(10분위)', '운형(운형약어)', '최저운고(100m )',
       '시정(10m)', '지면상태(지면상태코드)', '현상번호(국내식)', '지면온도(°C)', '지면온도 QC플래그',
       '5cm 지중온도(°C)', '10cm 지중온도(°C)', '20cm 지중온도(°C)', '30cm 지중온도(°C)',
        '지역', '망', '측정소코드', '측정소명', '측정일시', '주소']
df_21.drop(drop_cols, axis = 1, inplace = True)
df_22.drop(drop_cols, axis = 1, inplace = True)

In [154]:
df_21.tail()

,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),SO2,CO,O3,NO2,PM10,PM25,PM10_lag1,PM10_1
time,,,,,,,,,,,,,
2021-12-31 19:00:00,-6.4,0.0,2.2,250.0,34,0.003,0.4,0.025,0.020,26.0,8.0,24.0,27.000000
2021-12-31 20:00:00,-6.3,0.0,4.1,320.0,35,0.003,0.4,0.030,0.014,27.0,9.0,31.0,20.000000
2021-12-31 21:00:00,-6.7,0.0,4.8,320.0,36,0.003,0.4,0.033,0.011,20.0,8.0,28.0,20.000000
2021-12-31 22:00:00,-7.5,0.0,3.0,320.0,37,0.003,0.4,0.029,0.015,20.0,9.0,29.0,20.000000
2021-12-31 23:00:00,-7.7,0.0,2.9,320.0,38,0.003,0.4,0.026,0.016,20.0,9.0,23.0,38.937202

In [135]:
# time 변수를 index로 세팅
df_21.set_index('time', inplace = True)
df_22.set_index('time', inplace = True)

---

#### **<span style="color:blue">[2-5] 변수들의 결측치 처리</span>**

In [128]:
# df_21, df_22의 결측치 확인
df_21.isna().sum()

기온(°C)         0
강수량(mm)     7810
풍속(m/s)        2
풍향(16방위)       2
습도(%)          0
time           0
SO2          112
CO            80
O3            97
NO2           80
PM10         105
PM25          97
dtype: int64

In [129]:
# df_21, df_22의 변수 중 '강수량(mm)'의 결측치를 처리
df_21['강수량(mm)'].fillna(0, inplace = True)
df_22['강수량(mm)'].fillna(0, inplace = True)

In [130]:
# df_21, df_22의 남은 결측치를 처리
df_21.dropna(axis = 0, inplace = True)
df_22.dropna(axis = 0, inplace = True)

In [ ]:
# df_21, df_22의 결측치 재확인
print(df_21.isna().sum())
print(df_22.isna().sum())

---

#### **<span style="color:blue">[2-6] 전일 같은 시간 변수 추가</span>**

* 모델링에 유용한 변수로 전일 같은 시간(24시간 전) 미세먼지 농도 변수를 추가합니다. 
* 시계열 데이터 처리를 위한 shift 연산을 참고하세요.

In [136]:
# df_21, df_22의 index(time)를 month, day, hour 로 쪼개기 (year는 필요 없음)
df_21.head()

,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),SO2,CO,O3,NO2,PM10,PM25
time,,,,,,,,,,,
2021-01-01 01:00:00,-8.7,0.0,2.4,270.0,68,0.002,0.6,0.018,0.020,25.0,14.0
2021-01-01 02:00:00,-9.1,0.0,1.6,270.0,69,0.002,0.6,0.013,0.025,27.0,16.0
2021-01-01 03:00:00,-9.3,0.0,1.1,250.0,70,0.003,0.6,0.011,0.027,23.0,13.0
2021-01-01 04:00:00,-9.3,0.0,0.3,0.0,71,0.003,0.6,0.008,0.032,24.0,14.0
2021-01-01 05:00:00,-9.7,0.0,1.9,20.0,72,0.002,0.7,0.003,0.037,26.0,16.0

In [146]:
# df_21, df_22에 전일 같은 시간 미세먼지 농도 변수(PM10_lag1) 추가
# 전일 같은 시간은 24시간 전 입니다.
df_21['PM10_lag1'] = df_21['PM10'].shift(24)
df_22['PM10_lag1'] = df_22['PM10'].shift(24)

---

#### **<span style="color:blue">[2-7] t+1 시점의 미세먼지 농도 데이터 생성</span>**

* t+1 시점은 1시간 후 입니다.
* t+1 시점의 미세먼지 농도 변수를 생성하세요.
* t+1 시점의 미세먼지 농도는 머신러닝 모델을 통해 예측하려는 y값(target) 입니다.

In [147]:
# df_21, df_22에 t+1 시점 변수(PM10_1) 추가
df_21['PM10_1'] = df_21['PM10'].shift(-1)
df_22['PM10_1'] = df_22['PM10'].shift(-1)

In [148]:
# 결측치가 있다면 처리
mean_21 = df_21['PM10'].mean()

df_21['PM10_lag1'].fillna(mean_21, inplace = True)
df_21['PM10_1'].fillna(mean_21, inplace = True)

mean_22 = df_22['PM10'].mean()

df_22['PM10_lag1'].fillna(mean_22, inplace = True)
df_22['PM10_1'].fillna(mean_22, inplace = True)

---

#### **<span style="color:blue">[2-8] train, test 데이터 분리</span>**

* 21년도 데이터(df_21)를 train 데이터로 저장하세요. y 값을 제외하고 train_x로 저장한 후 y 값은 train_y로 저장하세요.
* 22년도 데이터(df_22)를 test 데이터로 저장하세요. y 값을 제외하고 test_x로 저장한 후 y 값은 test_y로 저장하세요.
* 각각의 데이터프레임을 csv 파일로 저장하세요. (train_x.csv / train_y.csv / test_x.csv / test_y.csv)
* y값은 'PM10_1' 즉, t+1 시점의 미세먼지 농도입니다.

In [149]:
# 아래에 필요한 코드를 작성하고 결과를 확인합니다.
target = 'PM10_1'

train_x = df_21.drop(target, axis = 1)
train_y = df_21.loc[:,target]

test_x = df_22.drop(target, axis = 1)
test_y = df_22.loc[:,target]

In [150]:
# 각각의 데이터프레임을 csv 파일로 저장 (train_x.csv / train_y.csv / test_x.csv / test_y.csv)

train_x.to_csv("C:/Users/admin/Desktop/에이블 실습/mini2/train_x.csv")
train_y.to_csv("C:/Users/admin/Desktop/에이블 실습/mini2/train_y.csv") 
test_x.to_csv("C:/Users/admin/Desktop/에이블 실습/mini2/test_x.csv") 
test_y.to_csv("C:/Users/admin/Desktop/에이블 실습/mini2/test_y.csv")